FROM node:20-alpine
WORKDIR /workspace
COPY package*.json ./
COPY backend/package*.json ./backend/
COPY frontend/package*.json ./frontend/
RUN npm install
RUN cd backend && npm install
RUN cd frontend && npm install
COPY . .
EXPOSE 3000
CMD ["sh", "-c", "cd frontend && npm run dev"]
