FROM node:20-alpine
WORKDIR /workspace
COPY package*.json ./
COPY server/package*.json ./server/
COPY client/package*.json ./client/
RUN npm install
RUN cd server && npm install
RUN cd client && npm install
COPY . .
EXPOSE 3000
CMD ["sh", "-c", "cd client && npm run dev"]
