FROM node:20-alpine

RUN apk add --no-cache curl

WORKDIR /opt/blog

COPY package.json package-lock.json ./

RUN npm install

COPY . .

EXPOSE 4567

CMD ["npm", "run", "dev"]

HEALTHCHECK --interval=5s --timeout=5s --start-period=10s --retries=3 \
  CMD curl --fail http://localhost:4567 || exit 1
