version: "3"

includes:
  deploy2aws:
    taskfile: ./taskfiles/aws-deployment.yml
    dir: .
  gcloud-server:
    taskfile: ./taskfiles/server-deployment.yml
    dir: .
  sync:
    taskfile: ./taskfiles/sync.yml
    dir: .
  setup:
    taskfile: ./taskfiles/setup.yml
    dir: .

tasks:
  setup:
    desc: Setup development environment
    cmds:
      - task: setup:run

  deploytogcpvm:
    desc: "Deploy to Google Cloud server"
    cmds:
      - task: gcloud-server:deploy

  deploy2aws:
    desc: "Deploy to AWS"
    cmds:
      - task: deploy2aws:run

  gcloud-server-ssh:
    desc: "SSH into Google Cloud server"
    cmds:
      - task: gcloud-server:ssh

  update-dns-record:
    desc: "Update Cloudflare A record to Google Cloud server IP"
    cmds:
      - task: gcloud-server:update-dns-record
