version: "3"

tasks:
  build-backend-js:
    cmds:
      - cd backend && npx tsc

  build-frontend-js:
    cmds:
      - npx esbuild backend/assets/js/application.ts --bundle --minify --outfile=backend/public/assets/application.js

  build-css:
    cmds:
      - npx tailwindcss -i backend/assets/css/application.css -o backend/public/assets/application.css --minify

  fingerprint-assets:
    cmds:
      - node scripts/fingerprint-assets.cjs

  build-assets:
    deps: [build-frontend-js, build-css]
    cmds:
      - task: fingerprint-assets

  create-backend-lambda-zip:
    cmds:
      - cd backend && zip -r dist/lambda.zip dist/ views/ public/ ../node_modules/ ../package.json -x "node_modules/.cache/*" -x "node_modules/.package-lock.json"
      - zip -ur backend/dist/lambda.zip config/

  build:
    cmds:
      - rm -rf backend/dist
      - npm ci
      - task: build-backend-js
      - task: build-assets
      - task: create-backend-lambda-zip

  terraform-apply:
    dir: infra/aws
    dotenv: ['../../.env']
    cmds:
      - terraform init
      - terraform apply -auto-approve
        -var="notion_token=${NOTION_TOKEN}"
        -var="content_notion_url=${CONTENT_NOTION_URL}"
        -var="terraform_state_bucket=${TERRAFORM_STATE_BUCKET}"

  sync-frontend-to-s3:
    cmds:
      - aws s3 sync backend/public/ s3://blog-frontend-bucket-607420117092 --delete

  deploy:
    deps: [terraform-apply, sync-frontend-to-s3]

  run:
    cmds:
      - task: build
      - task: deploy
